apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-o2jb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-o2jb
    app.kubernetes.io/part-of: tkrw-pr712-0075-0043-app
  name: devfile-sample-o2jb
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-o2jb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-o2jb
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0043-tenant/tkrw-pr712-0075-0043-app/devfile-sample-o2jb@sha256:60698c4e09249378569508caabd48b0d8cdc3ed7408274800e9137bb1a82907c
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
